
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import com.aluminati.onuw.ClientEvent;
import com.aluminati.onuw.Void;
import com.fasterxml.jackson.core.JsonProcessingException;
import io.dropwizard.jackson.DiscoverableSubtypeResolver;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.palantir.conjure.java.serialization.ObjectMappers;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        OnuwServer classUnderTest = new OnuwServer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
