
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.aluminati.onuw.OnuwServer;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        OnuwServer classUnderTest = new OnuwServer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
